### ISSUE TITLE
Problem position when detete a tag

### ISSUE THREAD

**Issue by phantuanphong** [DavidPizarro/AutoLabelUI#6]
onRemoveLabel(View view, int position). position value allway is -1 when i delete a tag. Something went wrong here?

**Comment by DavidPizarro** [comment]
Are you using a List like RecyclerView for example? Maybe you aren't using a List and you are using the method 'removeLabel(int position)'.

Remember that methods 'addLabel(String textLabel, int position)' and 'removeLabel(int position)' must be used ONLY with Lists (RecyclerView for example). The position is the place in the list, not the position of the label added.

So, you have to use the method 'removeLabel(String labelToRemove)'. Try this and tell me please!
