### ISSUE TITLE
getLabel problem

### ISSUE THREAD

**Issue by aragevorgyan** [DavidPizarro/AutoLabelUI#7]
I added this library to gradle in Android studio. When I try to call getLabel or getLabels methods it shows that there are no such methods and in .class file I don't see them.
What can be the reason?

**Comment by DavidPizarro** [comment]
OMG!
Yes, it seems an error with Maven Central. I'll upload a new version possibly today with these methods.
I'll write you when it has been uploaded.

**Comment by DavidPizarro** [comment]
Hi!
It has been solved in the new version 1.0.1.
Thanks!
