### ISSUE TITLE
Label shape

### ISSUE THREAD

**Issue by EpsilonOrionis** [DavidPizarro/AutoLabelUI#8]
Is it possible to change the shape? Rounded edges etc...?

**Comment by DavidPizarro** [comment]
Yes , I'll upload a new version possibly today.
I'll write you when it has been uploaded and I will explain you how to do this (very simple)

**Comment by EpsilonOrionis** [comment]
Thank you

**Comment by nitinmishra27** [comment]
@EpsilonOrionis even i was also searching for same, very thanks for your work

**Comment by DavidPizarro** [comment]
Hi!
It has been solved in the new version **1.0.1**. 

Now, `'background_color'`attribute with color reference has been removed. Now you can use the new **`'label_background_res'`** attribute. It can be a color or a drawable. **It's a reference, as you want.**
Also, `'setBackgroundColor'` method has been removed. Now you can use the new **`'setBackgroundResource'`** method. **You can use a color or a drawable, as you want and need.**
Also `'withBackgrondColor'` Builder method has been removed. Now you can use the new **`'withBackgrondResource'`** Builder method. **You can use a color or a drawable, as you want and need.**

Also,**`'label_padding'`** attribute, **`'setLabelPadding'`** method and **`'withLabelPadding'`** Builder method have been added.

Thanks!

**Comment by EpsilonOrionis** [comment]
Thank you again

**Comment by nitinmishra27** [comment]
@DavidPizarro Thanks for your quick work.....
