### ISSUE TITLE
Can not add to project by gradle

### ISSUE THREAD

**Issue by dinhthaidaica** [DavidPizarro/AutoLabelUI#9]
I tried to add this lib to to my project with `compile 'com.github.davidpizarro:autolabelui:VERSION'` to my gradle file but I receive the message `Error:(39, 13) Failed to resolve: com.github.davidpizarro:autolabelui:VERSION`

Please help...

**Comment by dinhthaidaica** [comment]
I'm sorry for misunderstanding , it should replace VERSION by 1.0.1 or other number of version. I'll close this issue.

**Comment by DavidPizarro** [comment]
;)
